import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | propertytaxcalc.net",
  description: "Read our legal and financial disclaimer regarding the use of propertytaxcalc.net tools.",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight text-gray-900 mb-8">Disclaimer</h1>
      <div className="prose prose-blue max-w-none text-gray-600">
        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-6 mb-8">
          <p className="text-lg font-medium text-yellow-800 mb-0">
            The tools and information on propertytaxcalc.net are provided for general educational purposes only. We are not a law firm, financial advisory service, or medical provider.
          </p>
        </div>
        
        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">No Professional Advice</h2>
        <p className="mb-6">
          The estimates generated by our calculators are based on standard industry formulas and user-provided inputs. They are strictly estimates and should not be relied upon as definitive legal, financial, tax, or medical advice. Actual costs, settlements, fees, and outcomes vary significantly based on jurisdiction, individual circumstances, and market conditions.
        </p>

        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">No Attorney-Client Relationship</h2>
        <p className="mb-6">
          Using this website or communicating with us does not create an attorney-client, financial planner-client, or doctor-patient relationship. You should not act or refrain from acting on the basis of any content included in this site without seeking appropriate professional advice.
        </p>

        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Affiliate and Advertising Disclosure</h2>
        <p className="mb-6">
          propertytaxcalc.net may display advertisements (such as Google AdSense) or affiliate links. We may receive compensation if you click on these links or purchase products through them. However, this does not influence our editorial content or the mathematical neutrality of our calculators.
        </p>
      </div>
    </div>
  );
}
